---
spring:
  config:
    activate:
      on-profile: local
    import: optional:file:local.env[.properties]

---

spring:
  config:
    activate:
      on-profile: prod
    import: optional:file:prod.env[.properties]
---

spring:
  profiles:
    active: local

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100

    database-platform: org.hibernate.dialect.PostgreSQLDialect


# OPEN DOC API 설정
springdoc:
  version: '1.0.0'
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /api-docs.html
    disable-swagger-default-url: true
    doc-expansion: full
  paths-to-match:
    - /v1/**
  cache:
    disabled: true